/**
 * Generates `supabase/seed-catalogue.sql` from `src/data/catalogue.ts`.
 *
 *   npm run seed:sql
 *
 * The admin dashboard has an "Import print catalogue" button that does the same
 * thing over the API, but that path needs a working admin account first. This
 * file runs in the Supabase SQL editor, which executes as `postgres` and so
 * bypasses row level security — which makes it the reliable way to get from an
 * empty database to a populated catalogue on a fresh project.
 *
 * Re-run it whenever the print catalogue in `src/data/catalogue.ts` changes.
 */
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";

// Node strips TypeScript types natively, so catalogue.ts imports directly.
const ROOT = path.resolve(import.meta.dirname, "..");
const { categories, bioCategory } = await import(
  pathToFileURL(path.join(ROOT, "src/data/catalogue.ts")).href
);

/** Single-quote a value for SQL, or NULL. */
const q = (v) =>
  v === null || v === undefined || v === "" ? "NULL" : `'${String(v).replace(/'/g, "''")}'`;

/** A Postgres text[] literal. */
const arr = (items) =>
  items.length === 0
    ? "'{}'"
    : `ARRAY[${items.map((i) => q(i)).join(", ")}]::text[]`;

/** A jsonb literal for the spec rows. */
const specs = (rows) => (rows?.length ? `${q(JSON.stringify(rows))}::jsonb` : "'[]'::jsonb");

const categoryImages = new Map(
  categories.map((c) => [c.id, [...new Set([c.thumb, c.heroImage, ...c.secondaryImages])]])
);
const seen = new Map();
function nextImage(categoryId) {
  const pool = categoryImages.get(categoryId) ?? ["/gallery/studio-trays-stack.webp"];
  const n = seen.get(categoryId) ?? 0;
  seen.set(categoryId, n + 1);
  return pool[n % pool.length];
}

const lines = [];
lines.push("-- Generated by scripts/generate-seed-sql.ts — do not edit by hand.");
lines.push("-- Loads the 2023 print catalogue into an empty database.");
lines.push("--");
lines.push("-- Run this in the Supabase SQL editor AFTER schema.sql. It is safe to run");
lines.push("-- more than once: existing codes are left exactly as they are, so prices you");
lines.push("-- have already set are never overwritten.");
lines.push("--");
lines.push("-- Products arrive published with no price, which the shop renders as");
lines.push('-- "price on request". Set a price and the line starts showing a real figure.');
lines.push("");
lines.push("begin;");
lines.push("");

// ---------------------------------------------------------------- categories
lines.push("-- Ranges. Products reference these by foreign key, so they go first.");
lines.push(
  "insert into public.categories (id, name, short_name, kicker, tagline, hero_image, thumb, theme, sort_order) values"
);
const catRows = [
  ...categories.map((c, i) => [c, i]),
  [bioCategory, categories.length],
].map(
  ([c, i]) =>
    `  (${q(c.id)}, ${q(c.name)}, ${q(c.shortName)}, ${q(c.kicker)}, ${q(c.tagline)}, ${q(
      c.heroImage
    )}, ${q(c.thumb)}, ${q(c.theme)}, ${i})`
);
lines.push(catRows.join(",\n"));
lines.push("on conflict (id) do update set");
lines.push("  name = excluded.name,");
lines.push("  short_name = excluded.short_name,");
lines.push("  kicker = excluded.kicker,");
lines.push("  tagline = excluded.tagline,");
lines.push("  hero_image = excluded.hero_image,");
lines.push("  thumb = excluded.thumb,");
lines.push("  theme = excluded.theme,");
lines.push("  sort_order = excluded.sort_order;");
lines.push("");

// ------------------------------------------------------------------ products
const productRows = [];
let order = 0;
for (const category of categories) {
  for (const group of category.groups) {
    for (const product of group.products) {
      productRows.push(
        `  (${q(product.code)}, ${q(product.description)}, ${q(category.id)}, ${q(
          group.name
        )}, ${q(product.size)}, ${Number.parseInt(product.casePack, 10) || 1}, ${q(
          group.material
        )}, ${q(group.materialCode)}, ${q(group.surface)}, ${arr(group.colors)}, ${arr(
          group.certs
        )}, ${specs(group.specs)}, ${q(group.highlight ?? group.note ?? null)}, ${arr([
          nextImage(category.id),
        ])}, ${order < 6}, ${order})`
      );
      order += 1;
    }
  }
}

lines.push(`-- ${productRows.length} product codes, straight off the print catalogue.`);
lines.push(
  "insert into public.products (code, name, category_id, group_name, size, case_pack, material, material_code, surface, colors, certs, specs, quality_notes, images, is_featured, sort_order) values"
);
lines.push(productRows.join(",\n"));
lines.push("on conflict (code) do nothing;");
lines.push("");
lines.push("commit;");
lines.push("");
lines.push("-- What landed:");
lines.push("select (select count(*) from public.categories) as ranges,");
lines.push("       (select count(*) from public.products) as products,");
lines.push("       (select count(*) from public.products where price is not null) as priced;");
lines.push("");

await mkdir(path.join(ROOT, "supabase"), { recursive: true });
const out = path.join(ROOT, "supabase/seed-catalogue.sql");
await writeFile(out, lines.join("\n"), "utf8");
console.log(
  `wrote supabase/seed-catalogue.sql — ${catRows.length} ranges, ${productRows.length} products`
);
